# Atividade 01: Etapa 01 --> Aula 02 - Python

## Dados númericos

In [3]:
# Variável interira - Comentário: linha não executada, utilizada para fornecer informações sobre o código
a = 1 # declara uma variável chamada "a" e atribui o valor inteiro 1 a ela
print('Valor de a = '+str(a)) # O comando 'print" imprime uma mensagem na tela que inclui o valor da variável a. str(a) é usado para converter o valor de a em uma string
type(a) #é uma função que retorna o tipo de dados da variável

Valor de a = 1


int

In [4]:
#Variável dupla precisão
b = 1.0 #b é uma variável que armazena um número real (ponto flutuante) com precisão dupla, ou seja, não é inteio como anteriormente
print(b) 
type (b)

1.0


float

In [5]:
#Converter float para int
c=int(b) #converte a variável criada anterioirmente em uma variável do tipo inteiro
print(c)
type(c)

1


int

In [7]:
#Declarando nan (Not a Number) 
import numpy as np #importa a biblioteca NumPy com um apelido np
d = np.nan #Esta linha atribui à variável d o valor np.nan, que representa um valor "Not a Number" (NaN), um conceito comumente utilizado em cálculos numéricos e científicos para representar valores indefinidos ou ausentes
print(d)
type(d)

nan


float

In [15]:
#Operação com NaN
e = d*1 #Esta linha realiza uma operação de multiplicação entre a variável d e o número 1. Como d é um nan, qualquer operação matemática envolvendo um nan resultará em outro nan
print(e) #Portanto, aqui como saída é printado "nan"
e = d+1 #Mesma situação descrita antes, operação com um NaN resulta em NaN
print(e)
e = np.nansum([d,1]) #np.nansum() é uma função da biblioteca NumPy que é utilizada para somar os valores dos elementos array ([d, 1]), ignorando os valores nan (Not a Number). Sendo o array estruturas de dados que armazenam uma coleção de elementos números, strings ou outros tipos de dados, podendo ser no formato de vetor (informações unidimensionais) ou matriz (multidimensional).
print(e) #Portanto, mesmo que d seja nan, a função irá somar o valor 1.

nan
nan
1.0


## Dados de texto

In [11]:
# Declaração de variável texto
f = 'Fábio'#Delcara a variável "f" como 'Fábio', e a delimita como string por meio das aspas
g = "Gabriel" #Mesma situação aneterioir, só que com aspas duplas
print(f)
print(g)
print(f+g) #imprime o valor sem espaço
print(f+' '+g) #imprime o valor com espaço ente os nomes 

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


## Dados tipo bol - lógica 

In [18]:
a == 1 #é uma expressão booleana em Python que compara o valor da variável a com o valor inteiro 1 atirbuído anteriormente, caso a seja igual a 1 retorna "True", caso contrário "False"

True

In [17]:
h = (a ==2) #Atribui à  variável h a expressão boleana "a ==2", como a é diferente de 2 ao printar h o resultado é "False"
print(h)
type(h)

False


bool

In [19]:
i = True #Atribui à variável "i" com o valor booleano "True" 
type(i)

bool

In [20]:
ii = 'True' ##Atribui à variável "ii" uma string descrita como "True" porque esta com aspas
type(ii)

str

## Operação de comparação 

In [22]:
#Operação == --> Verifica se as variáveis "a" e "b" são iguais, se sim retorna "True", caso contrátrio "False"
a == b

True

In [23]:
#Operação >< --> Verifica se "a" é maior que "b", como "a" == "b" retorna "False"
a>b

False

In [24]:
# Operação != --> Verifica se "a" e "b" são diferentes 
a!= b 

False

In [25]:
# Operação >= ou <= --> Verifica se a maior ou igual a b
a>=b

True

## Operações matemáticas

In [26]:
#Soma - Faz a soma das variáveis declaradas anteriormente "a" e "b"
a+b

2.0

In [27]:
# Soma e atribui valor 
ab = a+b #Atribui o valor da soma das variáveis "a" e "b"  à variável "ab"
print(ab)

2.0


In [30]:
#Multiplicação 
l = a*b #Faz a multiplicação da variável "a" e "b"
print("Não use l como nome de varíavel") #Informa para não usar "l" como variável, já que essa letra pode ser confundida com o número 1. Eu confundi inclusive, ao tentar implementar
j= a*b #Refaz a operação usando outro nome para a variável 
print(j)

Não use l como nome de varíavel
1.0


In [31]:
#Divisão 
a/b #Faz a divisão de "a" e "b"

1.0

In [32]:
# Potência
5**2 # Faz a operação de 5², ** representa o elevado à

25

In [34]:
#Operações matemáticas com biblioteca math
import math #Importa a biblioteca math
math.exp(10) #Chama a função math.exp(x), que retorna o valor da exponencial de x

22026.465794806718

In [35]:
math.exp(0) #Calcula a exponencial de 0

1.0

In [36]:
math.exp(a) # Calcula a exponencial da variável "a"

2.718281828459045

In [37]:
math.exp(-10)

4.5399929762484854e-05

In [38]:
import math as mt #importa a biblioteca math com um apelido mt
mt.log(c) #Calcula o logarítimo natural de "c"

0.0

In [39]:
mt.log10(100) #Calcula o logarítimo base 10 de 100

2.0

## Listas

In [43]:
myFristList = [1,2,3] #O código cria uma lista chamada myFristList contendo os elementos [1, 2, 3] e, em seguida, imprime essa lista. 
print(myFristList) #lista é uma estrutura de dados que armazena uma coleção ordenada de elementos. Cada elemento em uma lista pode ser de qualquer tipo de dados, como números, strings, booleanos, ou até mesmo outras listas.

[1, 2, 3]


In [44]:
#Acessando valores da lista pelo index
print(myFristList[0])
print(myFristList[2]) #Acessa valores específicos da lista myFristList pelos seus índices e os imprime, o índice é um número que representa a posição de um elemento em uma sequência

1
3


In [45]:
myFristList==a #Verifica se a lista é igual a variável "a"

False

In [46]:
myFristList[0]==a #Verifica se o elemento na posição 0 da lista é igual a "a"

True

In [47]:
mySecList = [1,a,'c']#Faz uma segunda lista com valores númericos, variáveis e um string
print(mySecList)

[1, 1, 'c']


In [48]:
type(mySecList)

list

In [49]:
type(mySecList[2])

str

In [50]:
type(mySecList[1])

int

## Caminhos = path

In [45]:
path = r"C:\ENS5173_MayaraDargas\ENS5173-2024.1_MayaraDargasSousa" #Atribui uma string à variável path e, em seguida, imprime essa string. Esta string corresponde a um caminho de diretório no sistema de arquivos do Windows
print(path) #O prefixo r antes das aspas indica uma string de "raw" (bruta) em Python. Isso significa que os caracteres de escape, como \n ou \t, não são interpretados, permitindo usar barras invertidas (\)

C:\ENS5173_MayaraDargas\ENS5173-2024.1_MayaraDargasSousa


In [36]:
path = "C:/ENS5173_MayaraDargas/ENS5173-2024.1_MayaraDargasSousa"#Para evitar problemas com "\", a barra inclinada para a direita "/" pode ser usada como um separador de diretório alternativo
print(path)

C:/ENS5173_MayaraDargas/ENS5173-2024.1_MayaraDargasSousa


In [46]:
import os # Importa o módulo "os" em seu programa Python. O módulo os fornece funções para interagir com o sistema operacional, como manipulação de arquivos, acesso ao sistema de arquivos, manipulação de caminhos de diretório, entre outras coisas
#Listar arquivos da pasta
os.listdir(path) #Isso chama a função listdir() do módulo "os". Esta função retorna uma lista contendo os nomes de entrada no diretório fornecido pelo caminho path. Portanto, os.listdir(path) está listando os arquivos e diretórios contidos no diretório especificado pelo caminho path

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'Aula01.ipynb',
 'inputs',
 'README.md',
 'scripts',
 'test',
 'venv']

In [47]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0] #Seleciona o arquivo na poisção 0 contida na lista anterior

'.git'

In [48]:
# Concatenando caminhos - constrói um caminho completo para o primeiro arquivo listado no diretório especificado por path
path+"/"+os.listdir(path)[0] #Essa parte concatena o caminho especificado por path com o nome do primeiro arquivo encontrado no diretório. Portanto, em termos simples, este código está construindo o caminho completo para o primeiro arquivo ou diretório dentro do diretório especificado por path, utilizando "/" como separador de diretório.

'C:\\ENS5173_MayaraDargas\\ENS5173-2024.1_MayaraDargasSousa/.git'

In [51]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'ORIG_HEAD',
 'packed-refs',
 'refs']

In [54]:
# Diretório que estou trababalhando
os.getcwd() #Função que retorna diretório de trabalho atual 

'C:\\Users\\mayar\\OneDrive\\Documentos'

In [55]:
# Mudo de diretório para o caminho 
os.chdir("C:\ENS5173_MayaraDargas\ENS5173-2024.1_MayaraDargasSousa")

In [56]:
os.getcwd() #Função que retorna diretório de trabalho atual 

'C:\\ENS5173_MayaraDargas\\ENS5173-2024.1_MayaraDargasSousa'

In [57]:
#Criando diretório - cria um novo diretório chamado "test" dentro do diretório de trabalho atual do programa
new_path = os.getcwd()+'/test' #Cria uma nova variável new_path que contém o caminho completo para o diretório de trabalho atual (os.getcwd()) concatenado com o nome do diretório que você deseja criar, neste caso, "test".

if os.path.isdir(new_path):#verifica se o caminho especificado em new_path corresponde a um diretório existente no sistema de arquivos
    print('diretório já existe')#Se sim, retorna "diretório já existe"
else:
    print('Criando diretório '+new_path)#Caso contrário, retorna "Criando diretório"
    os.mkdir(new_path)#Cria novo diretório com caminho especificado

diretório já existe


In [60]:
# Criando diretório
new_path = os.getcwd()+'/test2' #Cria uma nova variável new_path que contém o caminho completo para o diretório de trabalho atual (os.getcwd()) concatenado com o nome do diretório que você deseja criar, neste caso, "test2".

if os.path.isdir(new_path): #verifica se o caminho especificado em new_path corresponde a um diretório existente no sistema de arquivos
    print('diretório já existe') #Se o diretório já existir, o código dentro do bloco if será executado.
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file: #criam um arquivo de texto chamado "copy.txt" dentro do diretório "test2" e escrevem o texto "Your text goes here" dentro desse arquivo. O modo "w" indica que o arquivo será aberto para escrita. O bloco with garante que o arquivo será fechado automaticamente após a escrita.
        file.write("Your text goes here")
else:#Se o caminho especificado em new_path não corresponder a um diretório existente, o código dentro do bloco else será executado
    print('Criando diretório '+new_path) 
    os.mkdir(new_path) #cria um novo diretório com o caminho especificado em new_path utilizando a função os.mkdir().
    with open(new_path+"/copy.txt", "w") as file: #cria um arquivo de texto chamado "copy.txt" dentro do diretório recém-criado "test2" e escrevem o texto "Your text goes here" dentro desse arquivo. O modo "w" indica que o arquivo será aberto para escrita. O bloco with garante que o arquivo será fechado automaticamente após a escrita.
        file.write("Your text goes here") 

Criando diretório C:\ENS5173_MayaraDargas\ENS5173-2024.1_MayaraDargasSousa/test2


## Numpy arrays e Pandas DataFrames

In [2]:
import numpy as np #importa a biblioteca numpy como np 
# Criando uma variável numpy
n = np.array(0) #Utilizando a função np.array() do NumPy para criar um array numpy, passando o número inteiro 0 como argumento para a função. 
type(n)

numpy.ndarray

In [3]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55] #cria uma lista 
n = np.array(myThirdList) #converte lista em um array numpy
print(n)

[ 1  2  3 10 20 55]


In [4]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10) #A função np.random.rand() gera números aleatórios de uma distribuição uniforme entre 0 e 1. Os dois argumentos (10, 10) indicam que queremos uma matriz de tamanho 10x10.
print(n)
# Dimensões da matrix
print(n.shape) #imprime tamanho da matriz

[[0.61328738 0.74231872 0.08697741 0.08797987 0.34964056 0.66458839
  0.25423123 0.33689815 0.18634357 0.28729242]
 [0.17919999 0.91612454 0.37547959 0.96895078 0.59358987 0.22245341
  0.63329248 0.24446289 0.08674617 0.26720168]
 [0.54082959 0.50305426 0.31263228 0.76580402 0.44195992 0.23573714
  0.16924425 0.78797323 0.05836433 0.89790838]
 [0.84017841 0.46164118 0.18556116 0.88271871 0.51060745 0.5663127
  0.71920115 0.75815226 0.77837884 0.12854925]
 [0.46001909 0.48475844 0.95594494 0.78563971 0.1593947  0.40987403
  0.54250232 0.16563677 0.05545976 0.69764474]
 [0.02141006 0.30278413 0.34994358 0.52650258 0.77447081 0.06138093
  0.01744766 0.98585515 0.78153701 0.14889831]
 [0.08452312 0.21326523 0.9592332  0.95319746 0.55020908 0.01737797
  0.4046398  0.02349183 0.87279349 0.01349596]
 [0.46990639 0.07781391 0.91705805 0.06853045 0.14307341 0.89480969
  0.62976567 0.60705519 0.31556031 0.15251384]
 [0.07640586 0.56311757 0.84358711 0.81398179 0.44511514 0.65975303
  0.10520034 

In [7]:
# Acessando valores da matriz
n[0,:] #n é o nome da matriz criada anteriormente. [0,:]: Este é o operador de indexação do NumPy usando para acessar os elementos da matriz. O primeiro índice 0 indica a linha que se deseja acessar. Neste caso, 0 indica a primeira linha da matriz. O segundo índice indica que se deseja acessar todos os elementos da linha selecionada

array([0.61328738, 0.74231872, 0.08697741, 0.08797987, 0.34964056,
       0.66458839, 0.25423123, 0.33689815, 0.18634357, 0.28729242])

In [9]:
n[:,0] # primeiro: indica que se deseja acessar todos os elementos das linhas da matriz.O segundo indica que se deseja acessar apenas o elemento na primeira coluna de cada linha.

array([0.61328738, 0.17919999, 0.54082959, 0.84017841, 0.46001909,
       0.02141006, 0.08452312, 0.46990639, 0.07640586, 0.69573929])

In [11]:
n[:,1:5] #primeiro elemento acessa todas as linhas da matriz. Segundo elemento: 1:5 indica que você deseja acessar as colunas da segunda (índice 1) até a quinta (índice 4).

array([[0.74231872, 0.08697741, 0.08797987, 0.34964056],
       [0.91612454, 0.37547959, 0.96895078, 0.59358987],
       [0.50305426, 0.31263228, 0.76580402, 0.44195992],
       [0.46164118, 0.18556116, 0.88271871, 0.51060745],
       [0.48475844, 0.95594494, 0.78563971, 0.1593947 ],
       [0.30278413, 0.34994358, 0.52650258, 0.77447081],
       [0.21326523, 0.9592332 , 0.95319746, 0.55020908],
       [0.07781391, 0.91705805, 0.06853045, 0.14307341],
       [0.56311757, 0.84358711, 0.81398179, 0.44511514],
       [0.92218288, 0.55380815, 0.09661527, 0.49763451]])

In [12]:
n[0,1:5] #primeiro elemento acessa primeira linha (índice zero). Segundo elemento: 1:5 indica que você deseja acessar as colunas da segunda (índice 1) até a quinta (índice 4).

array([0.74231872, 0.08697741, 0.08797987, 0.34964056])

In [13]:
n[0,-1] #acessa o último elemento da primeira linha

0.28729242156015233

In [14]:
n[0,4:-1] #indica que você deseja acessar os elementos a partir da quinta coluna até o penúltimo elemento da linha. O índice -1 refere-se ao último elemento de uma sequência.

array([0.34964056, 0.66458839, 0.25423123, 0.33689815, 0.18634357])

In [15]:
n[0,4:] #acessa um intervalo de elementos da primeira linha da matriz n, começando da quinta coluna até o último elemento da linha

array([0.34964056, 0.66458839, 0.25423123, 0.33689815, 0.18634357,
       0.28729242])

In [17]:
an = np.log(n*5) #an = np.log(n*5) calcula o logaritmo natural (base e) de cada elemento da matriz n multiplicado por 5 e armazena o resultado em uma nova matriz chamada an
print(an)

[[ 1.12051627  1.31146133 -0.83266888 -0.82120934  0.55858829  1.20085052
   0.23992685  0.5214633  -0.07072525  0.36218322]
 [-0.10981492  1.52183495  0.62988674  1.57789645  1.08787126  0.10640031
   1.152615    0.20074615 -0.83533108  0.28968636]
 [ 0.99478687  0.92238067  0.44671032  1.34260893  0.79290184  0.1644
  -0.16697442  1.37114675 -1.23161246  1.50175067]
 [ 1.43529689  0.83647056 -0.07493282  1.48468922  0.93728372  1.04082904
   1.27982371  1.33256687  1.35889598 -0.44200523]
 [ 0.83295062  0.88533335  1.56438295  1.36818093 -0.22693382  0.71753249
   0.997875   -0.18852013 -1.28265968  1.24939264]
 [-2.23445662  0.41470275  0.55945457  0.96793887  1.35386261 -1.18121825
  -2.4391121   1.59519207  1.36294514 -0.29505378]
 [-0.86129231  0.06421923  1.56781685  1.56150471  1.01198099 -2.44311394
   0.70467993 -2.14166447  1.47338161 -2.69592733]
 [ 0.85421615 -0.9439971   1.52285341 -1.07103913 -0.33495948  1.49829369
   1.14703044  1.11030234  0.45603247 -0.27106205]
 [-0